return {
  ["workshop-2078243581"]={
    configuration_options={ Blue=0, Display="target", Green=0, Projectile=true, Red=1, Type="hit" },
    enabled=true 
  },
  ["workshop-2119742489"]={
    configuration_options={ Hunger_Cost=1, Ownership=false, Sanity_Cost=1 },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-569043634"]={
    configuration_options={
      Health_Penalty_Generic="Unchanged",
      Health_Penalty_Maximum="Unchanged",
      Health_Penalty_Meat_Effigy="Unchanged",
      Health_Penalty_Portal="Unchanged",
      Health_Respawn_Amount="Unchanged",
      KeepInventory="Unchanged",
      NoPlayerSkeletons="Unchanged",
      ReturnHotkey="Unchanged",
      ReturnHotkey_Mode="Closest",
      SpawnProtection="Unchanged",
      campfire="Enabled",
      coldfire="Enabled",
      coldfirepit="Enabled",
      firepit="Enabled",
      reviver="Unchanged",
      skeleton="Unchanged",
      usetags="Unchanged" 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  } 
}